config/routes.rb
Rails.application.routes.draw do
  resource :account, except: %i(new create destroy edit) do
    get 'token', on: :member
  end

  resources :entries do
    get 'freewrite', on: :member
  end

  # Sign-in and authentication.
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin'                  => 'sessions#new', as: :signin
  get '/signout'                 => 'sessions#destroy', as: :signout
  get '/auth/failure'            => 'sessions#failure'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :entries, only: %i(index)
    end
  end
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0

- flash.each do |type, contents|
  div class="alert alert-#{type.to_s == 'notice' ? 'success' : 'danger'}"
    button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×

    - if contents.is_a?(String)
      = content_tag :div, contents, id: "flash_#{type}"

    - elsif contents.is_a?(Hash)
      // Ignore hashes for now.
      / - contents.each do |name, problems|
      /   - problems.each do |problem|
      /     = "#{name} #{problem}"

    - elsif contents.is_a?(Array)
      - contents.each do |msg|
        = msg

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-collapse"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .navbar-brand= link_to 'Zen Writer', root_path

    .navbar-collapse.collapse aria-expanded='false'
      ul.nav.navbar-nav.navbar-left
        .vertical.separator
        li= link_to 'Entries', entries_path
      ul.nav.navbar-nav.navbar-left
        li= react_component 'SearchForm'

      ul.nav.navbar-nav.navbar-right
        - if signed_in?
          li= link_to account_path
            span: i.fi-widget
          li= link_to 'Sign out', signout_path

        - else
          li= link_to 'Sign in', signin_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title= content_for?(:title) ? yield(:title) : "Zen Writer"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'ZenWriter'}"
    = favicon_link_tag 'zenwriter-favicon.png'
    = stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = include_gon init: true
  body class="#{theme}"
    header
      = render 'layouts/navigation'
    main role="main"
      .container
        = render 'layouts/messages'
        = yield